### ISSUE TITLE
pb requirements.txt install psycopg2 & django

### ISSUE THREAD

**Issue by GregLebreton** [MarvinKweyu/AssessMe#19]
Hi, the requirements of pip install throws an error and the migrate command is looking for django.
Maybe I do something wrong, or the packages of the requirements aren't up-to-date.

**Comment by MarvinKweyu** [comment]
@GregLebreton Hi Greg, apologies for the late reply, the notification seems to have not crossed me. Mentions work too : )

I've seen what you mean.

1. Django installation
The requirement is listed. Should be installed. can you give the full traceback?

2. Database access
This is raised by the project trying to access the heroku database. I can split this setting to show the development settings as well for the local run.
