### ISSUE TITLE
project not running locally on windows environment  

### ISSUE THREAD

**Issue by Ken-Sarowiwa** [MarvinKweyu/AssessMe#28]
I am trying to run this project on my windows machine, i have created a virtual environment activated it and installed all the required dependencies.
but when i run python manage.py migrate i gert an error that python cannot open manage.py no such file or directory 

link to the image is below 
https://user-images.githubusercontent.com/33027235/154849210-83878b6c-aa0c-47c0-9862-feb9955e660b.png

**Comment by MarvinKweyu** [comment]
@Ken-Sarowiwa You are running this script from the `venv` directory instead of the root directory of the project

**Comment by Ken-Sarowiwa** [comment]
@MarvinKweyu i tried running  from the root directory but as you can see from the picture it inquired if i had activated the venv, running python manage.py migrate from the root directory wont work, not unless if i have installed django and all the dependencies globally. And we both know that is not correct way of doing things. That approach might bring alot of complications.

But the project runs smoothly on my linux(ubuntu 20.04) in the venv to be specific. i am running all commands from the venv

**Comment by MarvinKweyu** [comment]
Did you activate the virtual environment before?

Attach a copy of that traceback here. Write the steps to duplicate this erros. Step by step.
